#ifndef __NOVANIX_KERNEL_WIFI_VENDORS_H
#define __NOVANIX_KERNEL_WIFI_VENDORS_H


#define INTEL_VENDOR_ID    0x8086
#define QUALCOMM_VENDOR_ID 0x168C
#define BROADCOM_VENDOR_ID 0x14E4

#endif /*__NOVANIX_KERNEL_WIFI_VENDORS_H*/
