#ifndef _HEISEN_SCREEN_H
#define _HEISEN_SCREEN_H

#include <typing.hpp>

VOID InitScreen();
VOID PutPixel(INTEGER X,INTEGER Y,INTEGER RGB);
VOID PutRect(INTEGER X,INTEGER Y,INTEGER Width,INTEGER Height,INTEGER RGB);
VOID PutLine(INTEGER X1, INTEGER Y1, INTEGER X2, INTEGER Y2, INTEGER RGB);


#endif // _HEISEN_SCREEN_H